# Kanagawa Wave — hyprlock palette
$text_color   = rgba(C5C9C7FF)
$text_muted   = rgba(A4A7A4CC)
$accent_color = rgba(7FB4CAFF)
$check_color  = rgba(8A9A7BFF)
$fail_color   = rgba(C4746EFF)
$warn_color   = rgba(C4B28AFF)

$entry_background_color = rgba(0D0C0C88)
$entry_border_color     = rgba(7FB4CA44)

$font_family       = JetBrainsMonoNL Nerd Font
$font_family_clock = JetBrainsMonoNL Nerd Font
