# Open text files in nvim
protocol file
mime text/*
action launch --type=os-window nvim ${FILE_PATH}

# Open various code files in nvim
protocol file
ext rs,go,py,js,ts,jsx,tsx,c,cpp,h,hpp,json,yaml,yml,toml,sh,bash,zsh,conf
action launch --type=os-window nvim ${FILE_PATH}

# Open md code files in glow
protocol file
ext md
action launch --type=os-window glow ${FILE_PATH}

# Open images with feh
protocol file
mime image/*
action launch --type=background feh ${FILE_PATH}
