# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ROS2 and Foxglove visualization - open in workspace 3 and focus it
windowrule = workspace 3, match:class ^(rviz2)$
windowrule = workspace 3, match:class ^(foxglove)$
