[pyprland]
plugins = [
	"scratchpads",
	"lost_windows",
	# "monitors",
]


[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
lazy = true
allow_special_workspaces = true
margin = 40

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"
